// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UVguliCXm1kmTmsFPSvJKM5mZOZe2Ck',
    appId: '1:1068555216713:web:498704f42df7350a8f9c98',
    messagingSenderId: '1068555216713',
    projectId: 'th5-student-manager',
    authDomain: 'th5-student-manager.firebaseapp.com',
    storageBucket: 'th5-student-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD272Vs24rhDS0tf8IQThxpbS6K0qylfdU',
    appId: '1:1068555216713:android:e2951426dbbc42c18f9c98',
    messagingSenderId: '1068555216713',
    projectId: 'th5-student-manager',
    storageBucket: 'th5-student-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAr2NFaaQ1YH-PS0n4TLsTexBmGqyRWdQ',
    appId: '1:1068555216713:ios:479f0eb9990088398f9c98',
    messagingSenderId: '1068555216713',
    projectId: 'th5-student-manager',
    storageBucket: 'th5-student-manager.firebasestorage.app',
    androidClientId: '1068555216713-08r182j4ne4oke73fhto4aqrbfrqi5b9.apps.googleusercontent.com',
    iosClientId: '1068555216713-flt325qvevm75ber3b3eeav7ggkkoevq.apps.googleusercontent.com',
    iosBundleId: 'com.example.th5studentmanagerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAr2NFaaQ1YH-PS0n4TLsTexBmGqyRWdQ',
    appId: '1:1068555216713:ios:479f0eb9990088398f9c98',
    messagingSenderId: '1068555216713',
    projectId: 'th5-student-manager',
    storageBucket: 'th5-student-manager.firebasestorage.app',
    androidClientId: '1068555216713-08r182j4ne4oke73fhto4aqrbfrqi5b9.apps.googleusercontent.com',
    iosClientId: '1068555216713-flt325qvevm75ber3b3eeav7ggkkoevq.apps.googleusercontent.com',
    iosBundleId: 'com.example.th5studentmanagerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0UVguliCXm1kmTmsFPSvJKM5mZOZe2Ck',
    appId: '1:1068555216713:web:bc6cfe1c74997f5d8f9c98',
    messagingSenderId: '1068555216713',
    projectId: 'th5-student-manager',
    authDomain: 'th5-student-manager.firebaseapp.com',
    storageBucket: 'th5-student-manager.firebasestorage.app',
  );
}
